import { useState, type ChangeEvent, type FormEvent } from "react";
import type { CustomCustomerRequest } from "../types/journey";

const initial: CustomCustomerRequest = { name: "", business_type: "", customer_goal: "", requested_amount: 0, monthly_revenue: 0, monthly_obligations: 0, fico_n: 0, emp_length: "", home_ownership_n: "RENT", business_tenure_years: 0, purpose: "small_business", customer_identity_verified: false, required_documents_complete: false, existing_customer_relationship: false, recovery_allowed: true };

export function CustomCustomerForm({ onSubmit, onBack, error, submitting }: { onSubmit: (value: CustomCustomerRequest) => Promise<void>; onBack: () => void; error: string | null; submitting: boolean }) {
  const [form, setForm] = useState(initial); const [validation, setValidation] = useState<string | null>(null);
  const set = <K extends keyof CustomCustomerRequest>(key: K, value: CustomCustomerRequest[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: FormEvent) => { event.preventDefault();
    if (!form.name.trim() || !form.business_type.trim() || !form.customer_goal.trim() || !form.purpose.trim() || !form.emp_length.trim()) return setValidation("Complete all required text fields.");
    if (!Number.isFinite(form.requested_amount) || form.requested_amount <= 0 || form.monthly_revenue <= 0 || form.monthly_obligations < 0 || form.fico_n < 300 || form.fico_n > 850 || form.business_tenure_years <= 0) return setValidation("Enter valid positive amounts, tenure, and a FICO score from 300 to 850.");
    setValidation(null); void onSubmit(form);
  };
  const numeric = (key: "requested_amount" | "monthly_revenue" | "monthly_obligations" | "fico_n" | "business_tenure_years") => (event: ChangeEvent<HTMLInputElement>) => set(key, Number(event.target.value));
  return <form className="goal-form custom-customer-form" onSubmit={submit} noValidate>
    <div className="form-heading"><div><span className="eyebrow">CUSTOM CUSTOMER / SIMULATED PROTOTYPE</span><h2>Start a custom governed journey</h2></div><button className="button button-secondary" type="button" onClick={onBack}>Back to Demo Customers</button></div>
    <section><span className="eyebrow">01 CUSTOMER</span><div className="form-grid"><label>Customer name *<input value={form.name} onChange={(e) => set("name", e.target.value)} required /></label><label>Business type *<input value={form.business_type} onChange={(e) => set("business_type", e.target.value)} required /></label></div></section>
    <section><span className="eyebrow">02 GOAL</span><div className="form-grid"><label>Financial goal *<input value={form.customer_goal} onChange={(e) => set("customer_goal", e.target.value)} required /></label><label>Requested amount *<span className="amount-input"><span>₹</span><input type="number" min="1" value={form.requested_amount || ""} onChange={numeric("requested_amount")} required /></span></label></div></section>
    <section><span className="eyebrow">03 FINANCIAL PROFILE</span><div className="form-grid"><label>Monthly revenue *<input type="number" min="1" value={form.monthly_revenue || ""} onChange={numeric("monthly_revenue")} required /></label><label>Monthly obligations *<input type="number" min="0" value={form.monthly_obligations || ""} onChange={numeric("monthly_obligations")} required /></label></div><small>DTI is calculated by FinMate from monthly obligations ÷ monthly revenue.</small></section>
    <section><span className="eyebrow">04 CREDIT PROFILE</span><div className="form-grid"><label>FICO score *<input type="number" min="300" max="850" value={form.fico_n || ""} onChange={numeric("fico_n")} required /></label><label>Employment length *<select value={form.emp_length} onChange={(e) => set("emp_length", e.target.value)} required><option value="">Select</option><option>1 year</option><option>2 years</option><option>5 years</option><option>10+ years</option></select></label><label>Home ownership *<select value={form.home_ownership_n} onChange={(e) => set("home_ownership_n", e.target.value as CustomCustomerRequest["home_ownership_n"])}><option value="RENT">Rent</option><option value="OWN">Own</option><option value="MORTGAGE">Mortgage</option><option value="OTHER">Other</option></select></label><label>Business tenure (years) *<input type="number" min="1" value={form.business_tenure_years || ""} onChange={numeric("business_tenure_years")} required /></label><label>Loan / journey purpose *<input value={form.purpose} onChange={(e) => set("purpose", e.target.value)} required /></label></div></section>
    <section><span className="eyebrow">05 GOVERNANCE</span><div className="checkbox-grid">{([['customer_identity_verified', 'Identity verified'], ['required_documents_complete', 'Required documents complete'], ['existing_customer_relationship', 'Existing customer relationship'], ['recovery_allowed', 'Recovery allowed']] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={form[key]} onChange={(e) => set(key, e.target.checked)} />{label}</label>)}</div></section>
    {(validation || error) && <p className="form-note form-error" role="alert">{validation ?? error}</p>}<button className="button button-primary button-large" disabled={submitting} type="submit">{submitting ? "Starting governed journey…" : "Start Governed Journey →"}</button><p className="form-note">This stores simulated prototype context, then sends the normal journey request through n8n, XGBoost, SHAP, and policy.</p>
  </form>;
}
